### ISSUE TITLE
Unread count only updates after opening folder

### ISSUE THREAD

**Issue by ghost** [nedos/mutt-sidebar-patch#2]
When I open mutt any folder containing new emails says (1) regardless of how many unread emails are in the folder. Once opening the folder the number will update. Once I close mutt and open it again it goes back to just (1). 

If I downgrade mutt to the previous version and go back to the original Terry P. Chan patch which I'm assuming this is based off of, it works as expected.

**Comment by sjl** [comment]
+1, happens for me too

**Comment by nedos** [comment]
Works for me on a recent build.
